apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
         readinessProbe:
          httpGet:
            path: /nonexistent-health-check
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
