apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    # Custom health check that always reports unhealthy
    argocd.argoproj.io/health: |
      hs = {}
      hs.status = "Progressing"
      hs.message = "Custom health check - always progressing"
      return hs
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
